### ISSUE TITLE
读取进度后黑屏，加Q 1397257618

### ISSUE THREAD

**Issue by niyaode** [Focuxin/Hackintosh-ROG-B360i-8400#1]
我的配置和你一样。内存不一样。核显。在install   时读取进度时会黑屏，主板安照你的都调完了的。我用的是高清口 @Focuxin

**Comment by ion1ze** [comment]
> 我的配置和你一样。内存不一样。核显。在install 时读取进度时会黑屏，主板安照你的都调完了的。我用的是高清口 @Focuxin

你的MacOS版本是多少，等下我QQ加你吧

**Comment by niyaode** [comment]
macOS Catalina 10.15.5(19F101) Installer for Clover 5118 and WEPE Support UEFI and MBR

boss 快点啊 @Focuxin

**Comment by niyaode** [comment]
@Focuxin   不好意思 QQ 留错了
